// Croatian overlay for the template showcase - kept separate from catalog.js's
// English base (rather than a parallel `sites`/`stores` array) so the webp
// paths, live-demo URLs and industry→group mapping stay single-source and
// can't drift between locales. `categories` is keyed by the English `industry`
// string used in catalog.js (shared across many items - translate once, reuse),
// `items` by template slug (title + blurb only).
export default {
  sections: {
    simple: 'Jednostavne web stranice',
    ecommerce: 'Web trgovine',
  },

  // Industry paragraph per filter group (EN originals: GROUP_ABOUT in catalog.js).
  groupAbout: {
    'food-hospitality':
      'Dizajn za restorane, kafiće, barove, hotele i turističke tvrtke - jelovnici i ponude na prvom mjestu, primamljive fotografije, radno vrijeme, lokacija i istaknuta akcija za rezervaciju koja posjetitelje pretvara u goste.',
    'health-beauty':
      'Dizajn za salone, ordinacije, spa centre, trenere i wellness studije - usluge i cjenik jasno prikazani, sekcije tima i recenzija koje grade povjerenje te stalno vidljiva akcija za rezervaciju termina.',
    'home-pro':
      'Dizajn za obrte, agencije i profesionalne usluge - vodi s problemom koji rješavate, dokazuje kvalitetu projektima i recenzijama te potiče upite za ponudu jasnim pozivima na akciju i kontakt podacima.',
    'creative-media':
      'Dizajn za kreativne studije, fotografe, organizatore događanja i medijske brendove - radovi su u prvom planu kroz velike galerije i editorijalne rasporede, uz pakete i jasan tijek upita.',
    'tech-shop-edu':
      'Dizajn za digitalne proizvode, trgovine i edukacijske programe - brzo objašnjava ponudu, gradi kredibilitet značajkama, brojkama i recenzijama te vodi prema jednom cilju: registraciji, narudžbi ili upisu.',
    'sports-gaming':
      'Dizajn za klubove, akademije, događanja i gaming brendove - hrabri, energični rasporedi s terminima, postavama i novostima, uz istaknute akcije za ulaznice, prijave i članstva.',
    nightlife:
      'Upečatljiv dizajn za klubove i noćni život - program i lineupi u prvom planu, rezervacije stolova i guestlista, galerije s atmosferom i ugrađen Instagram feed.',
    'personal-community':
      'Dizajn za osobne brendove, udruge i zajednice - snažno predstavljanje, sekcije koje pričom grade povjerenje i jasne akcije za kontakt, učlanjenje ili donaciju.',
    ecommerce:
      'Potpuna višestranična online trgovina - početna, kolekcija, proizvod i košarica - s prodajnim sekcijama, pričom o proizvodu i tijekom kupnje spremnim za naplatu.',
  },

  simpleGroups: {
    all: 'Sve',
    'food-hospitality': 'Hrana i putovanja',
    'health-beauty': 'Zdravlje i ljepota',
    'home-pro': 'Dom i usluge',
    'creative-media': 'Kreativa i događanja',
    'tech-shop-edu': 'Tehnologija i trgovine',
    'sports-gaming': 'Sport i gaming',
    nightlife: 'Noćni život',
    'personal-community': 'Osobno',
  },

  categories: {
    'Food & Drink': 'Hrana i piće',
    'Real Estate': 'Nekretnine',
    'Beauty & Wellness': 'Ljepota i wellness',
    'Health & Medical': 'Zdravstvo',
    'Professional Services': 'Profesionalne usluge',
    'Home & Trades': 'Dom i obrti',
    'Creative & Design': 'Kreativa i dizajn',
    Events: 'Događanja',
    Personal: 'Osobno',
    Fitness: 'Fitness',
    'Hospitality & Travel': 'Ugostiteljstvo i putovanja',
    'Tech & Digital': 'Tehnologija i digitalno',
    'Retail & E-commerce': 'Maloprodaja i e-trgovina',
    'Education & Coaching': 'Edukacija i coaching',
    'Media & Creators': 'Mediji i kreatori',
    'Community & Nonprofit': 'Zajednica i udruge',
    Pets: 'Kućni ljubimci',
    Automotive: 'Automobilizam',
    'Games & Esports': 'Igre i esport',
    Sports: 'Sport',
    Retail: 'Maloprodaja',
    "Women's fashion": 'Ženska moda',
    Menswear: 'Muška moda',
    Streetwear: 'Streetwear',
    'Luxury fashion': 'Luksuzna moda',
    'Sustainable fashion': 'Održiva moda',
    Activewear: 'Sportska odjeća',
    Lingerie: 'Donje rublje',
    Denim: 'Traperice',
    Vintage: 'Vintage',
    Kidswear: 'Dječja odjeća',
    Footwear: 'Obuća',
    Eyewear: 'Naočale',
    'Leather goods': 'Kožna galanterija',
    Swimwear: 'Kupaći kostimi',
    'Eco footwear': 'Eko obuća',
    Accessories: 'Modni dodaci',
    Skincare: 'Njega kože',
    Makeup: 'Šminka',
    'Natural beauty': 'Prirodna kozmetika',
    Fragrance: 'Parfemi',
    Nightlife: 'Noćni život',
  },

  items: {
    '01-restaurant': { title: 'Restoran', blurb: 'Prikažite ambijent i kuhinju i povećajte broj rezervacija.' },
    '02-coffee-shop': { title: 'Kafić', blurb: 'Toplo predstavljanje brenda koje privlači goste u prostor.' },
    '03-real-estate-agency': { title: 'Agencija za nekretnine', blurb: 'Generirajte upite kupaca i prodavatelja za agenciju.' },
    '04-single-property-listing': { title: 'Oglas za jednu nekretninu', blurb: 'Prodajte jednu nekretninu uz detaljan prikaz.' },
    '05-hair-salon': { title: 'Frizerski salon', blurb: 'Promovirajte usluge i frizere te primajte rezervacije.' },
    '06-barbershop': { title: 'Brijačnica', blurb: 'Snažno predstavljanje brenda koje donosi termine.' },
    '07-beauty-spa-wellness': { title: 'Beauty spa i wellness', blurb: 'Prodajte pakete opuštanja i primajte rezervacije.' },
    '08-nail-salon': { title: 'Salon za nokte', blurb: 'Prikažite dizajne noktiju i pretvorite ih u rezervacije.' },
    '09-dental-clinic': { title: 'Stomatološka ordinacija', blurb: 'Izgradite povjerenje i zakažite nove preglede.' },
    '10-medical-practice': { title: 'Liječnička ordinacija', blurb: 'Predstavite ordinaciju i prikupljajte termine.' },
    '11-law-firm': { title: 'Odvjetnički ured', blurb: 'Izgradite autoritet i zakažite konzultacije.' },
    '12-financial-advisor': { title: 'Financijski savjetnik', blurb: 'Izgradite kredibilitet i zakažite konzultacije.' },
    '13-construction-company': { title: 'Građevinska tvrtka', blurb: 'Prikažite projekte i primajte upite za ponude.' },
    '14-home-services-plumbing-electric': { title: 'Kućne usluge', blurb: 'Pretvorite hitne lokalne upite u telefonske pozive.' },
    '15-cleaning-service': { title: 'Servis za čišćenje', blurb: 'Prodajte pakete usluga i primajte rezervacije.' },
    '16-landscaping-gardening': { title: 'Uređenje okoliša i vrtlarstvo', blurb: 'Prikažite transformacije prostora i prikupljajte upite.' },
    '17-interior-design-studio': { title: 'Studio za interijere', blurb: 'Prikažite portfolio i zakažite projekte.' },
    '18-architecture-firm': { title: 'Arhitektonski studio', blurb: 'Predstavite ključne projekte i mogućnosti studija.' },
    '19-photography-studio': { title: 'Fotografski studio', blurb: 'Prikažite radove i prodajte fotografske pakete.' },
    '20-wedding-planner': { title: 'Organizator vjenčanja', blurb: 'Prodajte vjenčanja iz snova i prikupljajte upite.' },
    '21-personal-profile-portfolio': { title: 'Osobni portfolio', blurb: 'Osobni brend i prikaz radova.' },
    '22-freelancer-consultant': { title: 'Freelancer / Konzultant', blurb: 'Prodajte svoju stručnost i pretvorite je u upite.' },
    '23-personal-trainer': { title: 'Osobni trener', blurb: 'Prodajte programe treninga i termine.' },
    '24-gym-fitness-studio': { title: 'Teretana i fitness studio', blurb: 'Povećajte broj članarina i probnih termina.' },
    '25-yoga-pilates-studio': { title: 'Yoga i Pilates studio', blurb: 'Smireno predstavljanje brenda koje donosi probne termine.' },
    '26-travel-agency': { title: 'Putnička agencija', blurb: 'Inspirirajte putovanja i prikupljajte upite.' },
    '27-boutique-hotel': { title: 'Butik hotel', blurb: 'Prikažite sobe i povećajte broj rezervacija.' },
    '28-vacation-rental-b-b': { title: 'Apartman za odmor / B&B', blurb: 'Predstavite smještaj i primajte rezervacije.' },
    '29-tour-operator': { title: 'Turoperator', blurb: 'Prodajte iskustva i putovanja.' },
    '30-saas-product': { title: 'SaaS proizvod', blurb: 'Pretvorite posjetitelje u probne korisnike i registracije.' },
    '31-mobile-app': { title: 'Landing stranica za mobilnu app', blurb: 'Povećajte broj preuzimanja aplikacije.' },
    '32-tech-startup': { title: 'Tech startup', blurb: 'Ispričajte priču i privucite zanimanje.' },
    '33-digital-marketing-agency': { title: 'Agencija za digitalni marketing', blurb: 'Dokažite rezultate i zakažite upoznavanje.' },
    '34-online-store-multi-product': { title: 'Online trgovina', blurb: 'Promovirajte trgovinu i istaknute proizvode.' },
    '35-single-product-dtc': { title: 'Jedan proizvod (DTC)', blurb: 'Uvjerljivo prodajte jedan hit proizvod.' },
    '36-online-course-e-learning': { title: 'Online tečaj', blurb: 'Upišite polaznike na tečaj.' },
    '37-life-coach': { title: 'Life coach', blurb: 'Zakažite upoznavanje i prodajte programe.' },
    '38-podcast': { title: 'Podcast', blurb: 'Povećajte broj slušatelja i pretplatnika.' },
    '39-author-book-launch': { title: 'Autor / Objava knjige', blurb: 'Prodajte knjigu i izgradite popis čitatelja.' },
    '40-musician-band': { title: 'Glazbenik / Bend', blurb: 'Promovirajte glazbu i povećajte broj pratitelja.' },
    '41-nonprofit-charity': { title: 'Neprofitna udruga', blurb: 'Povećajte broj donacija i volontera.' },
    '42-church-faith-community': { title: 'Crkva / Vjerska zajednica', blurb: 'Dočekajte posjetitelje i objavite raspored misa.' },
    '43-pet-grooming': { title: 'Salon za njegu ljubimaca', blurb: 'Prikažite kvalitetu njege i primajte rezervacije.' },
    '44-veterinary-clinic': { title: 'Veterinarska stanica', blurb: 'Izgradite povjerenje i zakažite preglede.' },
    '45-auto-repair-shop': { title: 'Autoservis', blurb: 'Pretvorite lokalne upite u dolaske na servis.' },
    '46-car-dealership': { title: 'Autosalon', blurb: 'Prikažite ponudu vozila i povećajte broj testnih vožnji.' },
    '47-bakery': { title: 'Pekarnica', blurb: 'Prikažite proizvode i povećajte narudžbe i posjete.' },
    '48-florist': { title: 'Cvjećarnica', blurb: 'Prodajte aranžmane za svaku prigodu.' },
    '49-catering-service': { title: 'Catering usluga', blurb: 'Prodajte catering za događanja i primajte upite za ponude.' },
    '50-daycare-preschool': { title: 'Jaslice i vrtić', blurb: 'Umirite roditelje i povećajte broj upisa.' },
    '51-crm-saas': { title: 'CRM platforma', blurb: 'Pretvorite timove u korisnike pametnijeg CRM-a besplatnom probom.' },
    '52-project-management-saas': { title: 'Aplikacija za upravljanje projektima', blurb: 'Prikažite tijek rada i povećajte broj probnih registracija.' },
    '53-ai-productivity-saas': { title: 'AI alat za produktivnost', blurb: 'Prodajte AI asistenta i privucite prve korisnike.' },
    '54-analytics-dashboard-saas': { title: 'Analitička platforma', blurb: 'Pretvorite podatke u demo i registraciju.' },
    '55-developer-tool-api-platform': { title: 'Razvojni alat / API platforma', blurb: 'Osvojite developere porukom fokusiranom na dokumentaciju.' },
    '56-cybersecurity-software': { title: 'Softver za kibernetičku sigurnost', blurb: 'Izgradite povjerenje i zakažite sigurnosni demo.' },
    '57-video-game-game-studio': { title: 'Studio za videoigre', blurb: 'Napravite hype za naslov i povećajte broj na wishlisti.' },
    '58-desktop-creative-software': { title: 'Kreativni softver', blurb: 'Prikažite aplikaciju i povećajte broj preuzimanja.' },
    '59-sports-club-team': { title: 'Sportski klub / Momčad', blurb: 'Okupite navijače uz raspored, novosti i ulaznice.' },
    '60-esports-team-org': { title: 'Esports organizacija', blurb: 'Prikažite postavu i povećajte bazu navijača.' },
    '61-sports-academy-coaching': { title: 'Sportska akademija', blurb: 'Popunite programe i prikupljajte prijave.' },
    '62-marathon-sporting-event': { title: 'Sportsko događanje', blurb: 'Povećajte broj prijava na utrku i sponzora.' },
    '63-insurance-agency': { title: 'Agencija za osiguranje', blurb: 'Izgradite povjerenje i prikupljajte upite za ponude.' },
    '64-accounting-tax-firm': { title: 'Računovodstveni i poreski ured', blurb: 'Izgradite autoritet i zakažite konzultacije.' },
    '65-recruitment-staffing-agency': { title: 'Agencija za zapošljavanje', blurb: 'Privucite i klijente i kandidate.' },
    '66-coworking-space': { title: 'Coworking prostor', blurb: 'Prikažite prostor i povećajte broj razgleda i članarina.' },
    '67-conference-summit': { title: 'Konferencija / Summit', blurb: 'Prodajte ulaznice i predstavite govornike.' },
    '68-jewelry-store': { title: 'Zlatarnica', blurb: 'Prikažite komade nakita i povećajte upite i posjete.' },
    '69-fashion-boutique': { title: 'Modni butik', blurb: 'Predstavite kolekcije i privucite kupce.' },
    '70-brewery-winery': { title: 'Craft pivovara', blurb: 'Ispričaj priču o zanatu i napuni točionicu gostima.' },
    '71-hairdressing-salon': { title: 'Frizerski atelje', blurb: 'Vrhunski salon: galerija, Instagram i online rezervacije.' },
    '72-hair-colour-studio': { title: 'Studio za boju kose', blurb: 'Glasni studio za boju: prije/poslije klizač i procjena cijene.' },
    '73-nail-studio': { title: 'Studio za nokte', blurb: 'Razigrana stranica za nokte: birač oblika, filtri galerije i rezervacija termina.' },
    '74-law-firm': { title: 'Odvjetničko društvo', blurb: 'Stranica butik odvjetničkog društva: pravni kompas, predmeti i jasne cijene.' },
    '75-startup-law': { title: 'Pravo za startupe', blurb: 'Moderna stranica za startup pravo: birač faze, fiksne cijene i popis poslova.' },
    '76-corporate-law': { title: 'Poslovna odvjetnička kuća', blurb: 'Etablirana odvjetnička kuća: pregled praksi, veliki poslovi i vremenska crta.' },
    '77-luxury-real-estate': { title: 'Luksuzne nekretnine', blurb: 'Stranica butik agencije: filmske rezidencije, brzi pregled i privatni razgledi.' },
    '78-fine-dining-restaurant': { title: 'Fine dining restoran', blurb: 'Restoran s degustacijskim menijem: meniji, vinski podrum i rezervacije stola.' },
    '79-caffe-bar': { title: 'Caffe bar', blurb: 'Koncept za stvarni zagrebački caffe bar: cjenik, događanja i rezervacije.' },
    '80-tattoo-studio': { title: 'Tattoo studio', blurb: 'Atelijerski studio za tetovaže: artisti, flash dropovi i rezervacije.' },

    'e01-womens-fashion-boutique': { title: 'Butik ženske mode', blurb: 'Potpuna online trgovina za brend ženske mode.' },
    'e02-mens-tailored-clothing': { title: 'Muška krojena odjeća', blurb: 'Prodajte krojenu mušku odjeću uz elegantnu trgovinu.' },
    'e03-streetwear': { title: 'Streetwear trgovina', blurb: 'Hrabra trgovina vođena dropovima za streetwear brend.' },
    'e04-luxury-fashion-house': { title: 'Luksuzna modna kuća', blurb: 'Editorijalna trgovina za luksuzni brend.' },
    'e05-sustainable-apparel': { title: 'Održiva odjeća', blurb: 'Prodajte odgovornu odjeću uz trgovinu vođenu pričom.' },
    'e06-activewear-athleisure': { title: 'Sportska odjeća i athleisure', blurb: 'Prodajte performansnu sportsku odjeću uz dinamičnu trgovinu.' },
    'e07-lingerie-intimates': { title: 'Donje rublje', blurb: 'Elegantna, intimna trgovina za brend donjeg rublja.' },
    'e08-premium-denim': { title: 'Premium traperice', blurb: 'Prodajte premium selvedge traperice uz trgovinu vođenu zanatom.' },
    'e09-vintage-thrift': { title: 'Vintage i second-hand', blurb: 'Trgovina s karakterom za unikatne vintage komade.' },
    'e10-kids-clothing': { title: 'Dječja odjeća', blurb: 'Vesela, roditeljima prilagođena trgovina za dječju odjeću.' },
    'e11-sneakers-footwear': { title: 'Tenisice i obuća', blurb: 'Dinamična trgovina za brend tenisica i obuće.' },
    'e12-eyewear-sunglasses': { title: 'Naočale i sunčane naočale', blurb: 'Prodajte okvire i sunčane naočale uz vizualno oštru trgovinu.' },
    'e13-handbags-leather-goods': { title: 'Torbe i kožna galanterija', blurb: 'Profinjena trgovina za torbe i kožnu galanteriju.' },
    'e14-swimwear': { title: 'Kupaći kostimi', blurb: 'Sunčana trgovina za brend kupaćih kostima.' },
    'e15-eco-sneakers': { title: 'Eko tenisice', blurb: 'Prodajte održive tenisice uz trgovinu vođenu pričom.' },
    'e16-accessories-scarves-hats': { title: 'Modni dodaci, šalovi i šeširi', blurb: 'Svestrana trgovina za modne dodatke.' },
    'e17-skincare': { title: 'Njega kože', blurb: 'Prodajte čistu njegu kože uz smirenu, kliničku trgovinu.' },
    'e18-makeup': { title: 'Šminka', blurb: 'Živopisna trgovina za brend dekorativne kozmetike.' },
    'e19-natural-organic-beauty': { title: 'Prirodna i organska kozmetika', blurb: 'Prodajte prirodnu kozmetiku uz botaničku trgovinu vođenu pričom.' },
    'e20-perfume-fragrance': { title: 'Parfemi i mirisi', blurb: 'Sugestivna trgovina za parfemsku kuću.' },

    'nc01-beton': { title: 'Klub BETON', blurb: 'Underground techno klub - sirov, brutalistički identitet koji klub čini vidljivim na Googleu. (Tier 1)' },
    'nc02-volt': { title: 'Klub VOLT', blurb: 'Energičan komercijalni klub - rezervacije stolova, guestlist i ulaznice koje donose zaradu. (Tier 2)' },
    'nc03-aurora': { title: 'AURORA Rooftop Club', blurb: 'Premium rooftop klub - interaktivni tlocrt, članstvo i analitička ploča za vlasnika. (Tier 3)' },
  },
}
